---
- name: Modificar Archivo de Configuracion
  hosts: all
  become: true

  tasks:
    - lineinfile:
       path: /etc/resolv.conf
       regexp: '^ nameserver'
       insertafter: '^#nameserver'
       line: 'nameserver 8.4.4.4'
